### ISSUE TITLE
Unlabeled data

### ISSUE THREAD

**Issue by hyjocean** [angus924/minirocket#13]
hello, thanks for your excellent work. 
wmm, and I have a problem, I find the response in "starting with "wide" data", you say the data can be unlabeled, it depends on my task "(You don't need labels necessarily, depending on your task.)"
and when I read your article or code readme, I notice that you mentioned the parameters in different data are same, right? (ok, I don't know if I understand right, and I can't find where is the latter information.)
So my question is, could I apply your work on my unlabeled data? if it's true, how can I set the "Y_traing" in examples codes?
thanks!

**Comment by angus924** [comment]
Hi @hyjocean, sorry for the slow reply.

In relation to labels, I didn't mean any 'special', only that you won't need labels for certain tasks (e.g., clustering, unsupervised training, etc.).

You don't need the labels to generate the features (i.e., `X_training_transform = transform(X_training, parameters)`), but you do need the labels when training the classifier (e.g., `classifier.fit(X_training_transform, Y_training)`).  If you don't have labels then you can't train the classifier in this way.

I hope that helps.

**Comment by hyjocean** [comment]
Ahh, I get it. 
Thanks for your patience reply~
