### ISSUE TITLE
Need example to use variable ROCKET

### ISSUE THREAD

**Issue by ramdhan1989** [angus924/minirocket#23]
Hi, would you mind providing examples to use minirocket_variable and minirocket_multivariate_variable? I am not sure on how to configure the required data input. 

thank you

**Comment by angus924** [comment]
Sorry for the slow reply.

The input format should be as follows:

- univariate: numpy float32 array, dimensions [n, l];
- multivariate: numpy float32 array, dimensions [n, c, l];

Where *n* is the number of time series (i.e., the batch dimension), *l* is time series length, and *c* is the number of channels (for multivariate input).  In other words, for univariate input, we have *n* time series, each of length *l*, and for multivariate input we have *n* time series, each with *c* channels, and each of length *l*.

I hope this helps.  Let me know if you have any other questions.
