### ISSUE TITLE
pls help to understand how your this repo code related to sktime.transformers.series_as_features.rocket

### ISSUE THREAD

**Issue by Sandy4321** [angus924/minirocket#25]
pls help to understand how your this repo code related to sktime.transformers.series_as_features.rocket
as written in 
https://towardsdatascience.com/minirocket-fast-er-and-accurate-time-series-classification-cdacca2dcbfa
from sktime.transformers.series_as_features.rocket import MiniRocket

is it the same code?

**Comment by angus924** [comment]
It should be essentially the same code, I contributed the original sktime code for Rocket, MiniRocket, etc.  However, I have not kept track of all the changes / refactoring that has taken place, so I can't guarantee that it's exactly the same.  From a quick look, the core code is the same.

I hope that helps.
