### ISSUE TITLE
is there any Tensorflow implementation of minirocket?

### ISSUE THREAD

**Issue by BrannonKing** [angus924/minirocket#4]
It would be handy to have minirocket as a Tensorflow layer (and potentially have it use the GPU if that's better in that scenario).

**Comment by angus924** [comment]
Hi @BrannonKing, unfortunately as far as I know there isn't a tensforflow implementation of MiniRocket at this stage.  Some kind of GPU implementation is on my to do list, but I'm not sure when I'll be able to get to it.  It might be possible to wrap the current CPU implementation into a tensorflow model, along the lines of what @oguiza has done with fastai / pytorch [here](https://github.com/timeseriesAI/tsai/blob/master/tsai/models/MINIROCKET.py).
