### ISSUE TITLE
download 10,000+ Training Examples

### ISSUE THREAD

**Issue by turmeric-blend** [angus924/minirocket#6]
hi, where can I download the MosquitoSound, InsectSound, and FruitFlies datasets?

**Comment by angus924** [comment]
Hi @turmeric-blend, you should be able to download them from http://timeseriesclassification.com/dataset.php.  Click on the relevant row in the table (you can also search for each dataset), then click "Download this dataset".

**Comment by turmeric-blend** [comment]
tq
